# Generated by Django 3.0.2 on 2020-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=30)),
                ('detail', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='home.jpg', max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
